exam({
  id: "exam-a",
  title: "Practice exam A",
  minutes: 100,
  blurb: "Weighted like the real exam. Sit it closed-book after Domain 1–2, or as a diagnostic on day one.",
  questions: [
    { domain: 1, q: "A company wants developers in a member account to have AdministratorAccess for their work but must be unable to disable the organization CloudTrail or create IAM users. Which control enforces this even if they attach AdministratorAccess?",
      choices: ["A permission boundary only on the CloudTrail service-linked role", "An SCP on the workloads OU denying cloudtrail:DeleteTrail, StopLogging, and iam:CreateUser", "A security group egress rule", "GuardDuty in the member account"],
      answer: 1, explain: "SCPs cap max permissions in member accounts. GuardDuty detects; it does not prevent IAM or Trail changes." },
    { domain: 1, q: "An application on Amazon EC2 must read objects from Amazon S3. Security forbids long-lived keys on disk. What should a solutions architect do?",
      choices: ["Create an IAM user and store the access key in /etc/environment", "Attach an IAM role to the instance profile with s3:GetObject on the bucket", "Embed root credentials in the AMI", "Make the bucket public and skip IAM"],
      answer: 1, explain: "Instance profile = temporary creds. Public buckets and root keys are never the design." },
    { domain: 1, q: "A mobile app with millions of users must upload photos to S3 without IAM users per customer. Uploads must be limited to a prefix per user.",
      choices: ["Cognito identity pool with a role whose policy scopes s3:PutObject to ${cognito-identity.amazonaws.com:sub}/*", "One IAM user shared in the app binary", "Disable Block Public Access and use PUT from anonymous", "AWS Artifact"],
      answer: 0, explain: "Identity pools mint temp creds. Scope with the identity ID in the policy." },
    { domain: 1, q: "A third-party monitoring vendor needs read-only CloudWatch in the company’s account. The company must avoid confused-deputy issues.",
      choices: ["Share an IAM user password on a wiki", "Cross-account role with an external ID that the vendor must pass on AssumeRole", "Turn on S3 Transfer Acceleration", "Open 443 from 0.0.0.0/0 to the AWS console"],
      answer: 1, explain: "External ID is the vendor AssumeRole pattern." },
    { domain: 1, q: "Private EC2 instances must call S3 and Amazon ECR without traversing the internet, and the company wants to cut NAT spend.",
      choices: ["Only a larger NAT gateway", "Gateway endpoint for S3 and interface endpoints for ECR APIs", "Public IP on every instance", "A Client VPN for each instance"],
      answer: 1, explain: "S3 uses a gateway endpoint; ECR needs interface endpoints. That removes this traffic from NAT." },
    { domain: 1, q: "An API on API Gateway is receiving SQL injection attempts. The API must keep serving legitimate traffic.",
      choices: ["AWS WAF with SQL injection managed rules associated to the API", "NACL deny on port 443 from the world", "Macie", "S3 Object Lock on the API"],
      answer: 0, explain: "L7 inspection is WAF. NACL would block everyone. Macie is S3 PII." },
    { domain: 1, q: "Security wants automatic detection of unusual API calls and possible compromised EC2 (crypto mining) using AWS-native telemetry.",
      choices: ["Amazon GuardDuty", "AWS WAF", "Amazon Rekognition", "AWS Glue"],
      answer: 0, explain: "GuardDuty consumes CloudTrail/VPC Flow/DNS (and more) for threat findings." },
    { domain: 1, q: "Objects in S3 must be encrypted with a key the security account can disable immediately. Decrypt operations must be auditable.",
      choices: ["SSE-S3 only", "SSE-KMS with a customer managed key and CloudTrail data/management events on KMS", "Client-side XOR in the app with no KMS", "Disable encryption to simplify audit"],
      answer: 1, explain: "CMK disable revokes future use; CloudTrail shows kms:Decrypt. SSE-S3 does not give that key-policy control." },
    { domain: 1, q: "Admins need a shell on instances in private subnets. Inbound SSH from the internet is forbidden. Least operational overhead?",
      choices: ["Bastion with SSH open to 0.0.0.0/0", "AWS Systems Manager Session Manager plus required endpoints or NAT", "FTP", "Public Elastic IPs and telnet"],
      answer: 1, explain: "Session Manager removes inbound 22. A wide-open bastion fails the constraint." },
    { domain: 1, q: "An auditor requests AWS’s SOC 2 Type II report for the shared-responsibility side AWS owns.",
      choices: ["Amazon Macie", "AWS Artifact", "VPC Flow Logs", "Personal Health Dashboard"],
      answer: 1, explain: "Artifact is the compliance report portal." },
    { domain: 1, q: "A company must store financial records in S3 so that even the account root cannot delete them during a 7-year retention.",
      choices: ["S3 Standard with a lifecycle to expire in 7 days", "S3 Object Lock in compliance mode with 7-year retention", "EBS snapshots in the same account with no lock", "CloudFront signed cookies"],
      answer: 1, explain: "Compliance-mode Object Lock is WORM. Root cannot shorten it." },
    { domain: 1, q: "RDS credentials must rotate every 30 days with minimal custom code. Applications should retrieve the current secret at runtime.",
      choices: ["Hard-code and a calendar reminder", "AWS Secrets Manager with rotation enabled for RDS", "Store the password in an unencrypted S3 object", "Put the password in the AMI"],
      answer: 1, explain: "Secrets Manager rotation is the managed RDS pattern." },
    { domain: 1, q: "A web application on EC2 was SSRF’d and the instance role was stolen via the metadata service. What design reduces this risk?",
      choices: ["Require IMDSv2 and shrink the instance role to least privilege", "Use the root user on the instance", "Disable all logging", "Put AdministratorAccess on the instance role so the app needs fewer calls"],
      answer: 0, explain: "IMDSv2 blocks most SSRF token fetches. Least privilege limits blast radius." },
    { domain: 1, q: "Network team owns a VPC in a network account. Application accounts must launch EC2 into those subnets without copying the VPC.",
      choices: ["VPC peering from every app account plus duplicate route tables by hand forever", "AWS Resource Access Manager subnet sharing (shared VPC)", "Make all subnets public", "AWS DataSync"],
      answer: 1, explain: "RAM shared subnets are the shared-VPC pattern." },
    { domain: 1, q: "TLS for an internet-facing ALB must auto-renew. Instances should not terminate TLS.",
      choices: ["ACM certificate on the ALB", "Copy an ACM public cert onto each EC2 (export)", "Self-signed certs in a security group", "WAF encryption"],
      answer: 0, explain: "ACM attaches to ALB and renews. Public ACM certs are not exportable to EC2." },
    { domain: 2, q: "A bursty upload API must not drop jobs when image workers are slow. Order is irrelevant.",
      choices: ["Synchronous call to a single EC2", "Amazon SQS Standard between API and workers", "SNS email only", "Store jobs as rows in a single-AZ MySQL and poll without a queue"],
      answer: 1, explain: "SQS is the durable buffer. RDS-as-queue is an anti-pattern." },
    { domain: 2, q: "An order event must be processed by billing, search, and analytics independently, each with its own retry and DLQ.",
      choices: ["One Lambda that calls all three inline", "SNS topic with three SQS subscriptions (or EventBridge to three queues)", "A shared EBS volume", "CloudFront invalidation"],
      answer: 1, explain: "Fan-out + durable per consumer." },
    { domain: 2, q: "HTTPS hostname: /api to ECS and /media to another target group. AWS WAF is required.",
      choices: ["Network Load Balancer", "Application Load Balancer with path rules and WAF", "Gateway Load Balancer", "Route 53 only"],
      answer: 1, explain: "Path routing + WAF = ALB (optionally behind CloudFront)." },
    { domain: 2, q: "A partner firewall can allow only two static IPs. The service is TCP, high packet rate, no HTTP features needed.",
      choices: ["ALB", "NLB with Elastic IPs", "S3 website hosting", "API Gateway REST"],
      answer: 1, explain: "Static IPs and L4 = NLB." },
    { domain: 2, q: "A container image in ECR runs 40 minutes. The team does not want to manage AMIs. Which compute?",
      choices: ["AWS Lambda", "Amazon ECS on AWS Fargate", "A Lambda function with a 40-minute timeout (invalid)", "Snowball Edge"],
      answer: 1, explain: "Lambda max is 15 minutes. Fargate runs the container without AMI patching." },
    { domain: 2, q: "A legacy application speaks JMS and cannot be changed this quarter. They need a managed broker on AWS.",
      choices: ["Amazon MQ", "SQS as a drop-in JMS server with zero code change guaranteed", "Neptune", "AWS WAF"],
      answer: 0, explain: "MQ exists for ActiveMQ/Rabbit/JMS compatibility." },
    { domain: 2, q: "Aurora PostgreSQL must survive the loss of an Availability Zone with automatic failover. The app connection string should keep working.",
      choices: ["Single Aurora instance in one AZ", "Aurora DB instances (or RDS Multi-AZ) in at least two AZs using the cluster endpoint", "SQS in front of SQL", "CloudFront in front of port 5432"],
      answer: 1, explain: "Multi-AZ database. CloudFront is HTTP." },
    { domain: 2, q: "Lambda functions in a VPC exhaust RDS connection limits and failover is slow.",
      choices: ["Amazon RDS Proxy", "Disable the VPC", "Public RDS with 0.0.0.0/0", "Replace RDS with S3 as the database"],
      answer: 0, explain: "RDS Proxy pools connections and improves failover behavior." },
    { domain: 2, q: "DR requirement: RPO 24 hours, RTO 8 hours, second Region, minimize cost.",
      choices: ["Active-active three Regions", "Daily AWS Backup / snapshot copies to the second Region (backup and restore)", "Aurora Global plus full-size always-on fleet in both Regions", "Pilot light is too cheap so they must overprovision"],
      answer: 1, explain: "Loose RPO/RTO → backup and restore. Don’t buy active-active." },
    { domain: 2, q: "DR requirement: MySQL-compatible, two Regions, RPO under 1 second, RTO a few minutes.",
      choices: ["Weekly AMI copy only", "Amazon Aurora Global Database", "S3 Standard-IA as the primary OLTP store", "SQS FIFO"],
      answer: 1, explain: "Aurora Global is built for that RPO/RTO pair with SQL." },
    { domain: 2, q: "A stateless web fleet must keep average CPU near 40% and replace unhealthy nodes automatically across two AZs.",
      choices: ["One huge EC2 with a CPU alarm email", "Auto Scaling group with target tracking, ELB health checks, subnets in two AZs", "Vertical scaling only", "Manual AMI copy once a year"],
      answer: 1, explain: "ASG + ELB + multi-AZ is the default HA web pattern." },
    { domain: 2, q: "S3 PutObject should run a 20-second thumbnail function. Traffic is idle at night and huge at noon.",
      choices: ["A 24/7 EC2 always on", "Lambda invoked by the S3 event notification", "A dedicated Oracle RAC", "AWS Direct Connect"],
      answer: 1, explain: "Short, event-driven, spiky = Lambda." },
    { domain: 2, q: "Users in two Regions must write session data locally with single-digit millisecond latency. Data is key-value, no SQL joins.",
      choices: ["A single-Region RDS", "DynamoDB Global Tables", "EFS One Zone", "AWS Snowball"],
      answer: 1, explain: "Global Tables is multi-active key-value." },
    { domain: 3, q: "Global offices upload 5 GB video files to a bucket in us-east-1. Uploads are slow over the public internet.",
      choices: ["S3 Transfer Acceleration", "EBS Magnetic in the office", "A security group on the S3 service", "Amazon RDS"],
      answer: 0, explain: "Transfer Acceleration uses edge locations to speed PUTs into a Regional bucket." },
    { domain: 3, q: "A Windows fleet needs a shared SMB file system joined to AWS Managed Microsoft AD, multi-AZ.",
      choices: ["Amazon EFS", "Amazon FSx for Windows File Server", "S3 Standard mounted as a drive with no gateway", "Instance store"],
      answer: 1, explain: "SMB + AD = FSx Windows. EFS is NFS." },
    { domain: 3, q: "Oracle on EC2 needs ~64,000 IOPS, sub-millisecond, and a cluster filesystem in one AZ.",
      choices: ["S3 Standard", "EFS bursting", "io2 Block Express with Multi-Attach", "sc1 HDD"],
      answer: 2, explain: "High IOPS clustered block is io2 Multi-Attach (same AZ)." },
    { domain: 3, q: "An HPC MPI job needs the lowest latency among 32 instances in one AZ.",
      choices: ["Spread placement group across Regions", "Cluster placement group with EFA", "CloudFront", "SQS"],
      answer: 1, explain: "Cluster PG is single-AZ low latency; EFA is the HPC NIC." },
    { domain: 3, q: "A MySQL application is read-heavy. Writes fit on the primary. Protocol must remain MySQL.",
      choices: ["Add Aurora/RDS read replicas and send reads to a reader endpoint", "Move OLTP to Amazon Redshift", "Single t3.micro Multi-AZ", "Store rows as objects in Glacier Deep Archive"],
      answer: 0, explain: "Read replicas scale reads. Redshift is a warehouse, not OLTP." },
    { domain: 3, q: "Gaming leaderboard: partition key gameId, sort key score, millions of items, serverless, single-digit ms.",
      choices: ["RDS SQL Server", "Amazon DynamoDB", "Amazon Redshift", "Amazon EFS"],
      answer: 1, explain: "Key-value access pattern at scale = DynamoDB." },
    { domain: 3, q: "Queries are ‘friends of friends’ on a social graph.",
      choices: ["Amazon Neptune", "S3 Select as the graph engine", "AWS CloudTrail", "Amazon EBS"],
      answer: 0, explain: "Graph = Neptune." },
    { domain: 3, q: "Identical SQL queries hammer RDS CPU from the app tier. Protocol is MySQL, not HTTP.",
      choices: ["CloudFront in front of port 3306", "ElastiCache Redis caching query results", "Disable Multi-AZ", "S3 Transfer Acceleration"],
      answer: 1, explain: "App cache. CloudFront does not speak MySQL." },
    { domain: 3, q: "A multiplayer game uses UDP, needs static anycast IPs, and should enter AWS at the nearest edge then ride the backbone.",
      choices: ["CloudFront only", "AWS Global Accelerator", "S3 static website", "Amazon EFS"],
      answer: 1, explain: "GA is non-HTTP anycast. CloudFront is HTTP cache." },
    { domain: 3, q: "Clickstream at 100,000 events/s must feed a custom real-time Lambda and also land in S3.",
      choices: ["Kinesis Data Streams (plus Firehose or Lambda to S3)", "One S3 PUT per click from each browser as the only buffer", "EBS snapshots", "ACM"],
      answer: 0, explain: "Streams handle ingest and fan-out. Per-event S3 PUT is not that pipeline." },
    { domain: 3, q: "Analysts want SQL on JSON files in S3 with no Hadoop cluster to manage.",
      choices: ["Amazon Athena and AWS Glue Data Catalog", "Unmanaged Hadoop on a single EC2 the intern SSHs into", "DynamoDB Scan from Excel", "CloudFront invalidations"],
      answer: 0, explain: "Athena is serverless SQL on S3." },
    { domain: 3, q: "Existing Kafka producers cannot change. They need a managed cluster on AWS.",
      choices: ["Amazon MSK", "SQS FIFO as a Kafka broker", "Amazon EFS", "AWS WAF"],
      answer: 0, explain: "MSK is Kafka-compatible. SQS is not the Kafka protocol." },
    { domain: 4, q: "Finance needs Slack when forecasted monthly AWS spend will exceed $50,000.",
      choices: ["AWS Budgets forecasted alert to SNS (then Slack)", "Amazon GuardDuty", "VPC Flow Logs as a billing tool", "S3 Inventory"],
      answer: 0, explain: "Budgets is the threshold/forecast alerter." },
    { domain: 4, q: "S3 access patterns are unknown and change. Minimize storage cost without hand-maintained lifecycle guesses.",
      choices: ["S3 Intelligent-Tiering", "Glacier Deep Archive for every new object", "io2 volumes", "S3 Standard forever with no review"],
      answer: 0, explain: "INT moves objects automatically. Deep Archive punishes frequent reads." },
    { domain: 4, q: "Legal archive for 7 years; restore in 12 hours is acceptable; lowest storage price.",
      choices: ["S3 Standard", "S3 Glacier Deep Archive", "Unexpiring EBS snapshots on gp3 as the archive plan", "CloudFront"],
      answer: 1, explain: "Deep Archive is the coldest class; 12h fits Flexible/Deep timing (Deep is 12–48h)." },
    { domain: 4, q: "Stateless image workers can retry. The company wants large compute discounts and can tolerate interruption.",
      choices: ["EC2 Spot (with diversification / mixed instances)", "Dedicated Hosts for every worker", "The largest metal On-Demand only", "AWS Snowball as compute"],
      answer: 0, explain: "Spot is for interruptible, retryable fleets." },
    { domain: 4, q: "Steady combined spend on EC2, Fargate, and Lambda. They want a 3-year discount but will change instance families.",
      choices: ["Compute Savings Plans", "A single Standard RI locked to i3.metal", "Spot for the primary RDS", "Buying office servers"],
      answer: 0, explain: "Compute SP covers those three and is family-flexible." },
    { domain: 4, q: "Private subnets pull terabytes per day from S3 in the same Region through a NAT gateway. First cost fix?",
      choices: ["S3 gateway VPC endpoint", "A fourth NAT gateway", "Replicate the bucket to four Regions", "Make the subnet public with no security groups"],
      answer: 0, explain: "Gateway endpoints take S3 off NAT. No hourly charge like interface endpoints." },
    { domain: 4, q: "An internal Postgres app is busy 9–5 weekdays and idle nights/weekends. Keep managed SQL; cut cost.",
      choices: ["Aurora Serverless v2 or scheduled stop/start of RDS", "The largest Oracle RAC always on", "DynamoDB Global Tables in four Regions", "Direct Connect"],
      answer: 0, explain: "Scale-to-low/pause idle SQL. Global Tables would cost more and change the model." },
    { domain: 4, q: "Need highly available outbound internet from private subnets; cost is secondary.",
      choices: ["One NAT in a single AZ for all private subnets", "NAT gateway in each AZ that has private subnets", "No NAT", "AWS CloudTrail"],
      answer: 1, explain: "NAT is AZ-scoped. HA = NAT per AZ. Cost-secondary is stated." },
    { domain: 4, q: "A 200 TB on-premises Hadoop dataset must move to S3 in two weeks. The WAN is 100 Mbps.",
      choices: ["Copy over the 100 Mbps VPN and hope", "AWS Snowball/Snow Family devices", "Email hard drives to a developer", "S3 Transfer Acceleration from a single laptop"],
      answer: 1, explain: "Petabytes/terabytes vs a thin WAN in a deadline → Snow. Rough math: 200 TB on 100 Mbps is many weeks." },
    { domain: 4, q: "Cost allocation by team in Athena with maximum billing granularity.",
      choices: ["Screenshots of Cost Explorer", "Cost and Usage Report to S3 plus cost allocation tags, queried with Athena", "CloudFront access logs only", "IAM Access Analyzer"],
      answer: 1, explain: "CUR is the detailed export; tags make it attributable." },
    { domain: 3, q: "Users must download objects over HTTPS without making the S3 bucket public.",
      choices: ["Turn off Block Public Access", "Amazon CloudFront with origin access control (OAC)", "FTP on EC2", "Object ACLs public-read on every object"],
      answer: 1, explain: "OAC lets CloudFront fetch privately. Bucket stays locked down." }
  ]
});
