exam({
  id: "exam-b",
  title: "Practice exam B",
  minutes: 100,
  blurb: "Harder stems, more ‘choose two,’ more cost vs HA conflicts. Take this after exam A, not the same day.",
  questions: [
    { domain: 1, q: "A company uses AWS Organizations. Security must guarantee that no member account can launch EC2 outside eu-west-1, even with AdministratorAccess.",
      choices: ["An IAM policy on one user in the security account", "An SCP on the relevant OUs denying RunInstances unless aws:RequestedRegion is eu-west-1", "A security group in eu-west-1", "Amazon Macie"],
      answer: 1, explain: "Region guardrails are SCPs. An IAM policy in another account does not bind member admins." },
    { domain: 1, q: "Account A’s Lambda must read a KMS-encrypted bucket in Account B. Which pair is required?",
      choices: ["Only an identity policy on Lambda in A", "Identity policy on the Lambda role in A, bucket policy in B, and KMS key policy in B allowing that role", "Make the key AWS-owned and the bucket public", "Enable Transfer Acceleration"],
      answer: 1, explain: "Cross-account encrypted S3 needs identity + bucket + CMK. Public is not a substitute." },
    { domain: 1, q: "Developers must create IAM roles for apps but must not be able to create a role that can escalate to AdministratorAccess.",
      choices: ["Permission boundaries on the developers and on roles they create", "Disable CloudTrail", "Put AdministratorAccess on every developer to save time", "WAF on IAM"],
      answer: 0, explain: "Permission boundaries are the delegated-admin ceiling. WAF does not protect IAM APIs." },
    { domain: 1, q: "A three-tier app: ALB, ECS, RDS. RDS must accept TCP only from the ECS tasks, not from a CIDR that might include other apps later.",
      choices: ["RDS security group allowing the ECS tasks’ security group on 3306", "NACL allow 3306 from 0.0.0.0/0", "Public accessibility enabled on RDS", "WAF on RDS"],
      answer: 0, explain: "SG-to-SG is least privilege and tracks the fleet as it scales." },
    { domain: 1, q: "The company needs a DDoS response team, cost protection against scaling bills during an attack, and extra L3/L7 protections on CloudFront.",
      choices: ["Shield Standard only (already included) and hope", "AWS Shield Advanced", "Amazon Macie", "S3 Object Lock"],
      answer: 1, explain: "Shield Advanced is the named product for DRT + cost protection." },
    { domain: 1, q: "Findings from GuardDuty, Inspector, and Macie must appear in one place with a CIS score across accounts.",
      choices: ["AWS Security Hub (with delegated admin)", "Amazon Rekognition", "AWS Elastic Beanstalk", "Amazon MQ"],
      answer: 0, explain: "Security Hub aggregates and scores standards." },
    { domain: 1, q: "An AMI encrypted with a CMK must be launchable in a second account in the same Region.",
      choices: ["Make the AMI public and email the CMK plaintext", "Share the AMI and grant the other account kms:CreateGrant/Decrypt on the CMK", "Disable encryption", "Copy to S3 as plaintext"],
      answer: 1, explain: "Share the AMI and the key. Never send key material." },
    { domain: 1, q: "On-premises must connect to AWS with ~5 Gbps consistent bandwidth and an encrypted failover path.",
      choices: ["Internet Gateway only", "Direct Connect as primary and Site-to-Site VPN as backup", "Client VPN on one laptop", "VPC peering to the office LAN"],
      answer: 1, explain: "DX + VPN is the textbook hybrid HA pair. You cannot peer to on-prem." },
    { domain: 1, q: "A data lake on S3 must be reachable only from a specific VPC endpoint. Any other path, including from the same account via internet, should fail.",
      choices: ["Bucket policy Deny unless aws:SourceVpce equals the endpoint ID, plus Block Public Access", "Disable Block Public Access", "Security group on S3 (there isn’t one like EC2)", "NACL on the S3 public service"],
      answer: 0, explain: "Condition keys on the bucket policy bind access to the endpoint." },
    { domain: 1, q: "Which service discovers credit-card numbers in S3 without building a custom scanner?",
      choices: ["Amazon Macie", "AWS Shield", "Amazon Elastic Transcoder", "AWS Glue crawler as the PII product"],
      answer: 0, explain: "Macie is the sensitive-data discovery service for S3." },
    { domain: 1, q: "Org CloudTrail logs must be tamper-resistant in a dedicated log-archive account.",
      choices: ["Trail writing to an S3 bucket in the log-archive account with restricted bucket policy, versioning, and Object Lock or MFA delete", "Trail writing to a bucket in each production account that developers own", "Disable logging to save money", "Store trails only in CloudWatch Logs with 1-day retention"],
      answer: 0, explain: "Central bucket + lock/versioning. Production-owned buckets can be deleted by admins." },
    { domain: 1, q: "A company wants a new multi-account landing zone with Account Factory and mandatory guardrails and least setup effort.",
      choices: ["Hand-roll 40 accounts with no SCP", "AWS Control Tower", "Amazon Cognito user pools as the org", "AWS Batch"],
      answer: 1, explain: "Control Tower is the opinionated landing zone." },
    { domain: 1, q: "TLS certificates for CloudFront must be issued by ACM. Where must the certificate live?",
      choices: ["ap-southeast-1 because the team is in Singapore", "us-east-1 (N. Virginia)", "On each EC2 origin only", "In AWS Artifact"],
      answer: 1, explain: "CloudFront requires ACM certs in us-east-1." },
    { domain: 1, q: "Which is AWS’s responsibility under the shared responsibility model for Amazon RDS?",
      choices: ["The guest OS and database engine patching of the managed service", "The customer’s schema, IAM, and security groups", "The application SQL injection bugs", "Classifying the customer’s PII"],
      answer: 0, explain: "RDS shifts OS/engine patching to AWS. You still own data, IAM, SGs, encryption config." },
    { domain: 1, q: "A web ACL must be deployed to every ALB in every account in the Organization automatically.",
      choices: ["AWS Firewall Manager", "Manually clicking each ALB monthly", "Amazon Macie", "AWS Snowball"],
      answer: 0, explain: "Firewall Manager centrally applies WAF/SG/Shield policies." },
    { domain: 2, q: "An ASG sits behind an ALB. Instances pass EC2 status checks but the app is dead. They are not replaced.",
      choices: ["Enable ELB health checks on the Auto Scaling group so failed target-health replaces instances", "Turn off the ALB", "Use a placement group cluster across three Regions", "Put the database in the ASG"],
      answer: 0, explain: "ASG EC2 health is not app health. ELB health checks close that gap." },
    { domain: 2, q: "A workflow: validate → wait for human approval → run EMR → notify. Retries and a visual state machine are required.",
      choices: ["A single 15-minute Lambda with Thread.sleep for days", "AWS Step Functions", "SQS as a full BPM engine with no extra service", "CloudFront"],
      answer: 1, explain: "Step Functions is the orchestrator (wait, approval, EMR integration)." },
    { domain: 2, q: "A SaaS partner can emit events. Multiple internal services should subscribe with payload filters and the company wants archive/replay.",
      choices: ["Amazon EventBridge partner event bus", "FTP", "EBS snapshots of the SaaS", "IAM Access Analyzer"],
      answer: 0, explain: "EventBridge partner integrations + archive/replay are the cue." },
    { domain: 2, q: "ECS tasks are stateless. The team does not want to patch container-host AMIs. Peak is 20× night-time.",
      choices: ["ECS on Fargate with service auto scaling", "A single always-on GPU metal for nginx", "Lambda with a 2-hour timeout", "Snowball"],
      answer: 0, explain: "Fargate removes AMI ops; service scaling handles 20×. Lambda cannot run 2 hours." },
    { domain: 2, q: "A company needs Kubernetes APIs and existing Helm charts. They will run on AWS.",
      choices: ["Amazon EKS", "Lambda only", "Amazon SQS as a scheduler for pods", "S3 static hosting"],
      answer: 0, explain: "Helm/K8s → EKS. ECS is not Kubernetes." },
    { domain: 2, q: "A single NAT gateway in AZ A serves private subnets in AZ A, B, and C. AZ A fails. What happens and what is the HA fix?",
      choices: ["Nothing; NAT is Regional magic. Keep one.", "Outbound from B and C that used that NAT fails; deploy a NAT in each AZ (and AZ-local routes)", "RDS fails because NAT is the database", "CloudFront replaces NAT automatically"],
      answer: 1, explain: "NAT GW is AZ-scoped. Per-AZ NAT + routes is HA (and avoids extra cross-AZ bytes)." },
    { domain: 2, q: "RTO of 2 minutes, RPO near zero, two Regions, users can use either Region for HTTP. Data is DynamoDB.",
      choices: ["Nightly backups only", "DynamoDB Global Tables plus latency-based Route 53 or Global Accelerator to regional stacks", "A single-AZ RDS", "Pilot light with RTO of hours"],
      answer: 1, explain: "Tight numbers + two Regions + key-value → Global Tables + active-active front door." },
    { domain: 2, q: "An app cannot be changed. It holds sticky in-memory sessions. The architect still needs multiple EC2s behind an ALB.",
      choices: ["ALB sticky sessions (and plan a later move to ElastiCache)", "S3 Transfer Acceleration", "NLB path routing (NLB cannot)", "Disable the second AZ"],
      answer: 0, explain: "When the app cannot change, stickiness is the crutch. Shared session store is better if you can change the app." },
    { domain: 2, q: "Service quotas in the DR Region were never raised. During failover, RunInstances throttles.",
      choices: ["Quotas are global and always infinite", "Request quota increases in the standby Region before disaster; test failover", "Shield Advanced raises EC2 quotas automatically", "Use the root user to skip quotas"],
      answer: 1, explain: "Quotas are Regional. Untested DR is a quota outage." },
    { domain: 2, q: "Messages must be processed in order per customer ID, with exactly-once processing semantics, at moderate throughput.",
      choices: ["SQS Standard", "SQS FIFO with message group ID = customer ID", "SNS SMS", "CloudWatch alarm"],
      answer: 1, explain: "FIFO + group ID preserves per-customer order. Standard is unordered." },
    { domain: 2, q: "CloudFront must keep serving a static site if the primary S3 origin is deleted or failing.",
      choices: ["CloudFront origin failover to a second origin (replica bucket in another Region)", "A security group on CloudFront", "Disable caching", "RDS Multi-AZ"],
      answer: 0, explain: "Origin groups / failover is the CloudFront HA pattern for origins." },
    { domain: 2, q: "A company wants immutable infrastructure for EC2 web fleets when a new AMI is released.",
      choices: ["SSH and yum update on Friday", "ASG instance refresh (or a blue/green swap) with the new launch template", "Change the running instance’s user data in place only", "Put AMI on a sticky session"],
      answer: 1, explain: "Replace instances from a new template. Don’t snowflake-patch prod." },
    { domain: 2, q: "API Gateway in front of Lambda is being invoked by a buggy client in a tight loop. Downstream DynamoDB is hot.",
      choices: ["API Gateway throttling / usage plans (and Lambda reserved concurrency)", "Make DynamoDB public", "Turn off IAM", "NAT gateway rate limiting HTTP paths"],
      answer: 0, explain: "Throttle at the door; reserved concurrency sheds load. NAT is not an HTTP rate limiter for API GW." },
    { domain: 3, q: "A CMS on many Linux EC2s in two AZs needs a shared POSIX file system with high durability.",
      choices: ["EBS Multi-Attach gp3 across AZs (not supported that way)", "Amazon EFS (Regional)", "S3 mounted with a FUSE hack as the exam answer", "Instance store RAID"],
      answer: 1, explain: "EFS is the multi-AZ NFS. EBS Multi-Attach is same-AZ and not general-purpose shared ext4." },
    { domain: 3, q: "Unpredictable traffic, PostgreSQL-compatible, avoid picking instance sizes, nights are idle.",
      choices: ["Aurora Serverless v2", "SQL Server on the largest EC2 left on", "DynamoDB with SQL JOIN support (it doesn’t)", "Snowball Edge"],
      answer: 0, explain: "Serverless v2 ACUs. Dynamo is not Postgres SQL." },
    { domain: 3, q: "DynamoDB has a hot partition and microsecond reads are required for that table.",
      choices: ["Amazon DynamoDB Accelerator (DAX)", "CloudFront in front of the DynamoDB low-level protocol", "Glacier Instant Retrieval", "AWS WAF on DynamoDB"],
      answer: 0, explain: "DAX is the Dynamo-specific cache. CloudFront is HTTP to origins you configure, not the Dynamo API as a CDN in the usual design." },
    { domain: 3, q: "On-premises NFS servers must keep their protocol. Files should land in S3 over time without rewriting apps.",
      choices: ["AWS Storage Gateway (File Gateway)", "Delete NFS and hope", "Amazon Rekognition", "AWS WAF"],
      answer: 0, explain: "File Gateway presents NFS/SMB and stores objects in S3." },
    { domain: 3, q: "A 50 Gbps instance-to-instance HPC requirement inside one AZ.",
      choices: ["t3.micro and a security group", "Large enough instances with enhanced networking in a cluster placement group", "S3 Transfer Acceleration between the two ENIs", "SQS"],
      answer: 1, explain: "Bandwidth scales with instance size; cluster PG + ENA/EFA for HPC." },
    { domain: 3, q: "A data warehouse of 20 TB with BI tools using SQL, plus occasional queries over extra data already in S3.",
      choices: ["Amazon Redshift (with Spectrum for S3)", "RDS MySQL as a 20 TB warehouse of choice", "SQS", "ACM"],
      answer: 0, explain: "Redshift is the warehouse; Spectrum extends to S3." },
    { domain: 3, q: "CSV logs should be converted to Parquet and cataloged for Athena with least cluster ops.",
      choices: ["AWS Glue jobs + crawler/catalog", "A standing EMR cluster that is never used off-hours and never right-sized, as the only option", "Manual Excel", "CloudFront"],
      answer: 0, explain: "Glue is the serverless ETL/catalog path. EMR is valid if they need a custom cluster, not ‘least ops.’" },
    { domain: 3, q: "Private hosted zone DNS from on-premises must resolve names in a VPC, and vice versa.",
      choices: ["Route 53 Resolver inbound/outbound endpoints (hybrid DNS)", "Public Route 53 only", "CloudFront", "GuardDuty as DNS"],
      answer: 0, explain: "Resolver endpoints are the hybrid DNS product." },
    { domain: 3, q: "A user-facing Lambda API has unacceptable cold starts. Cost is acceptable.",
      choices: ["Provisioned concurrency", "Move the function to Glacier", "Disable the memory setting", "Use FTP"],
      answer: 0, explain: "Provisioned concurrency keeps environments warm." },
    { domain: 3, q: "MongoDB API compatibility is required on a managed AWS service.",
      choices: ["Amazon DocumentDB", "Amazon Neptune only", "Amazon QLDB as Mongo", "Amazon EFS"],
      answer: 0, explain: "DocumentDB is Mongo-compatible. Neptune is graph." },
    { domain: 3, q: "Need signed URLs so a user can download one S3 object for 5 minutes without a public bucket.",
      choices: ["S3 presigned URL (or CloudFront signed URL)", "Disable Block Public Access for the whole bucket forever", "IAM user keys in the browser", "Open 80 on RDS"],
      answer: 0, explain: "Presigned/signed URLs are time-boxed object access." },
    { domain: 3, q: "An ALB-fronted app is global. Dynamic HTML cannot be cached long, but static assets can. Lowest latency for assets.",
      choices: ["CloudFront with two cache behaviors (long TTL on /static, short/no cache on HTML)", "Global Accelerator as an image cache", "EFS in one AZ for all global users", "A single NAT"],
      answer: 0, explain: "CloudFront cache behaviors. GA does not cache objects." },
    { domain: 4, q: "gp2 EBS volumes are overprovisioned for IOPS. First cost step before buying Savings Plans?",
      choices: ["Migrate to gp3 and right-size with Compute Optimizer / metrics", "Buy a 3-year Standard RI on the wrong family", "Convert all volumes to io2 Block Express", "Copy volumes to another Region for luck"],
      answer: 0, explain: "Right-size and gp3 first. Don’t lock a 3-year plan on waste." },
    { domain: 4, q: "A Redshift cluster is used 30 minutes a day for a report. It sits idle On-Demand otherwise.",
      choices: ["Pause the cluster (or Redshift Serverless) when idle", "Leave it", "Replicate to five Regions", "Put it behind CloudFront"],
      answer: 0, explain: "Pause/serverless matches bursty BI. Five Regions is the expensive joke answer." },
    { domain: 4, q: "Interface VPC endpoints were created for every AWS service in every AZ ‘just in case,’ including unused ones. Bills rose.",
      choices: ["Interface endpoints have hourly ENI charges; keep only the endpoints you need, use gateway endpoints for S3/DynamoDB", "Endpoints are always free", "Delete the VPC instead", "Buy Dedicated Hosts to make endpoints cheaper"],
      answer: 0, explain: "Interface endpoints cost money. Gateway endpoints for S3/Dynamo are the cheap/free path." },
    { domain: 4, q: "Non-production EC2 is unused 12 hours every night.",
      choices: ["Instance Scheduler / stop-start or ASG desired capacity 0 on a schedule", "The largest On-Demand 24/7", "Multi-Region active-active for dev", "Shield Advanced on each dev box"],
      answer: 0, explain: "Stop or scale to zero. Don’t HA-overbuy nonprod." },
    { domain: 4, q: "A company can use ARM. They want better price/performance for Linux web fleets without changing architecture much.",
      choices: ["Graviton-based instance types (after testing)", "Mainframe on Outposts as the cheap web tier", "Always Intel metal", "Spot for RDS primary with RPO 0 and no replicas"],
      answer: 0, explain: "Graviton is the standard price/performance lever when the stack supports ARM." },
    { domain: 4, q: "S3 holds millions of tiny log files Athena scans daily. The bill is high for both storage requests and scans.",
      choices: ["Compact to larger Parquet files, partition, and lifecycle old partitions", "Transition every 1 KB object to Deep Archive hourly and query it live", "Enable Transfer Acceleration on queries", "Store logs on io2 Multi-Attach"],
      answer: 0, explain: "Small files and text scans are expensive. Compact + columnar + partition." },
    { domain: 4, q: "They need a discount on a known, flat m7g fleet in one Region for three years and will not change family.",
      choices: ["Standard RI or EC2 Instance Savings Plan can beat Compute SP on discount if flexibility is unused", "Spot for the stateful un-replicated database only", "No commitment product exists", "Buy CloudFront as compute"],
      answer: 0, explain: "If you truly will not change, instance-specific commitments discount more. Compute SP is the flexible default." },
    { domain: 4, q: "Cross-AZ data transfer between chatty microservices is expensive. HA is still required.",
      choices: ["Keep replicas in two AZs but place chatty pairs together where possible and cut extra chatter; don’t go single-AZ", "One AZ for everything to save money, ignoring HA", "Replicate every packet to another Region", "Disable encryption"],
      answer: 0, explain: "The stem still requires HA. Optimize placement/chattiness; don’t delete the second AZ." },
    { domain: 4, q: "Idle Application Load Balancers and unattached Elastic IPs were found. Where does AWS surface these cost checks?",
      choices: ["AWS Trusted Advisor (cost category) and Cost Explorer", "Amazon Macie", "Amazon Rekognition", "AWS Artifact SOC report as a bill"],
      answer: 0, explain: "Trusted Advisor cost checks + Explorer. Artifact is compliance PDFs." },
    { domain: 4, q: "A team over-provisioned Lambda memory ‘for safety’ on a high-volume function. CPU is idle.",
      choices: ["Right-size memory (Lambda CPU tracks memory) using metrics/Compute Optimizer; over-memory can waste money", "Set memory to 10 GB on every function", "Always use provisioned concurrency for nightly batch", "Put the function in two extra Regions"],
      answer: 0, explain: "Memory is a cost and CPU knob. Idle extra memory is waste; CPU-bound functions may still want more memory." },
    { domain: 1, q: "Choose TWO. A solutions architect is designing encryption for EBS and S3. The company must use customer-managed keys and be able to revoke access quickly. Which two actions apply?",
      multi: true, choose: 2,
      choices: ["Use KMS CMKs with key policies granting only required roles", "Use SSE-S3 only because it is customer managed", "Disable the CMK (or remove grants) to revoke", "Share the CMK plaintext with application developers in Slack"],
      answer: [0, 2], explain: "CMK + disable/schedule-delete/remove grants. SSE-S3 is not a CMK. Never share key material." }
  ]
});
